### ISSUE TITLE
python3.9 pip3 install -r requirements.txt Error

### ISSUE THREAD

**Issue by chosen1cwp** [jwenjian/artline-demo#14]
Error information

pip3 install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement torch==1.6.0
ERROR: No matching distribution found for torch==1.6.0

Please advise me

thanks very much！

**Comment by chosen1cwp** [comment]
https://download.pytorch.org/whl/torch_stable.html  未能找到 Python3.9版本 对应的 1.6.0，降低Python版本至3.8 解决

**Comment by jwenjian** [comment]
@chosen1cwp thanks for the reply, if anyone meet the same issue, try downgrade the python version to 3.8
