### ISSUE TITLE
abot  ArtLine_650.pkl

### ISSUE THREAD

**Issue by sunxiao1983** [jwenjian/artline-demo#2]
docker bulid error  lack of Artline_650.pkl ,please owner check in.

**Comment by jwenjian** [comment]
The file is too large to add into repository, please download it manually then put it in the project folder before run docker build

**Comment by sunxiao1983** [comment]
oh,thanks .where can  download artline_650 pkl?dropbox?

**Comment by jwenjian** [comment]
yes, from the dropbox url

**Comment by sunxiao1983** [comment]
What a pity. Unfortunately, we can't access Dropbox in China. may I give you an email address for send Artline_ 650.pkl
It's also good to send my email or upload the image to dockerhub.

**Comment by jwenjian** [comment]
maybe I can draft a release tag and upload the pkl as attachment, will update you once completed

**Comment by sunxiao1983** [comment]
That's good, thank you

**Comment by jwenjian** [comment]
@sunxiao1983  you can download here https://github.com/jwenjian/artline-demo/releases/download/v0.1.0/ArtLine_650.pkl
